### ISSUE TITLE
Session Submission Page

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#2]
Needs to be created and made to work!

**Comment by ThatGuyCND** [comment]
Session submission is available trough the admin dashboard - iirc, we had presenters create user accounts (the only real users stored in the DB) so that we could leverage the dashboard.

need to ensure:
- default event is 2016 when creating new session (/node/add/sess)
- current user is autopop'd as speaker
- speaker role is added to new user accounts
- only non-admin fields are present for speaker role

@JCL324 anything I'm missing?

**Comment by mherchel** [comment]
hmmm... we also need a sessions page - we had one before. I know before we had a button on the top of that, which linked to the submission page.

**Comment by ultimike** [comment]
*  Default event set to 2016.  
*  Current user is auto populated as speaker.  
*  So, we want all new user accounts to get the "Speaker" role, correct? If so, we can do that with Rules. Please confirm.  
*  "Only non-admin fields are present for speaker role"? Not sure what you mean here - are you talking about on a user's "edit" page? If so, this is confirmed (I just gave the "test-1" user the "Speaker" role and confirmed they don't have access to user status, roles, etc...)  

@mherchel Are you talking about http://fldrupalcampstg.prod.acquia-sites.com/sessions-approval???

thanks,  
-mike

**Comment by ThatGuyCND** [comment]
Users shouldn't have access to admin fields on the session edit page.

**Comment by ultimike** [comment]
@ThatGuyCND Confirmed - users with only the "Speaker" role do not have access to any admin fields on the session add/edit pages. 

Anyone want to chime in on whether or not all new users automatically get the "Speaker" role?

thanks,  
-mike

**Comment by mherchel** [comment]
Tested. This works. Closing. 
![image](https://cloud.githubusercontent.com/assets/1605905/12484505/a40d3a44-c028-11e5-8007-2185415fa9c7.png)
