### ISSUE TITLE
What's up with the attendees view?

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#29]
What needs to be done to get the attendees view synced with EB? Does anyone want to tackle this? @JCL324 @iribarne @rje1953 @Tcraw77813 @jeppy64

**Comment by JCL324** [comment]
Taking a look now.

**Comment by JCL324** [comment]
Rick, I'm going to pass this on to you and Christian. First, all the Bio nodes currently are saying "new" and not sure why they would be updated.  Second, the EventID needs to be updated, is this hardcoded?  I'm pretty sure this year's is 19970715949 which if you look at the filters on the Attendees view, that's what I set if for.  There are currently 11 people signed up for this year.

**Comment by Tcraw77813** [comment]
As per your first question, I believe that has to do with the custom EB Integration module. On cron the module goes and gets attendee bios from their API and adds them to the queue. It then processes the items and updates the bios accordingly. When we were testing the module back in December, the database still had around 100-150 items in the queue so that's likely why people's bio are being updated. 
As far as the EventID goes I was told that someone had created a new Event on the site for this year's camp. The ID is a field in the event so it can be updated there.

**Comment by JCL324** [comment]
But somewhere - in the code? - it sets the EB id for all the nodes being imported?  The problem is that it shouldn't be bringing in last year's attendees at all, only this year's.

**Comment by Tcraw77813** [comment]
It queries all events in the system (in this case there are two) and then iterates over them. The EB ID is pulled out from the field during each iteration and then the API is called and returns all the attendees registered for that particular event. I can add a line of code that will only query 'published' nodes. This way as long as previous event(s) have been set to 'unpublished' then it will only pull in bios for the current year's event.

**Comment by JCL324** [comment]
Sounds good.  Is it not possible to just ignore the past event(s)?  Sounds like extra work that isn't necessary.

**Comment by Tcraw77813** [comment]
If you didn't want to add anymore code the only way that I see it being possible to 'ignore' the old event would be to delete it from the system. I'm not sure if you want to do that or not so that's why i suggested the code approach. The new code would be at most five lines, so it's not that big of a deal if we take that route.

**Comment by JCL324** [comment]
Christian, I've investigated a bit further and it doesn't appear that any of this year's attendees are coming over.  There are currently 15 registered for 2016 and I don't see them on the Drupal side.  They should have the event id of 19970715949 so they show up on https://www.fldrupal.camp/community/attendees.  It appears that all the Bio nodes have 15502173418 which is last year's id.  I've unpublished all of them.

**Comment by jeppy64** [comment]
Hey Guys,

Not sure if this helps tracking the issue, but I remember vaguely, while
building the new architecture last year that I had put entity reference
prepopulate in the mix very early on. My foggy old brain memory says... the
idea was that each event had it's own event id value, so, when bios were
created against a specific event (as child nodes through Relativity), the
event id became part of the bio nodes url alias. This would allow specific
bio nodes relative to an event and of course allow the same bio to reside
on multiple events for display.

What I don't remember is.... was that taken out in lieu of Alex's module
controlling things on the bio side?

J


On Tue, Jan 26, 2016 at 2:55 AM, John Learned <notifications@github.com>
wrote:

> Christian, I've investigated a bit further and it doesn't appear that any
> of this year's attendees are coming over. There are currently 15 registered
> for 2016 and I don't see them on the Drupal side. They should have the
> event id of 19970715949 so they show up on
> https://www.fldrupal.camp/community/attendees. It appears that all the
> Bio nodes have 15502173418 which is last year's id. I've unpublished all of
> them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mherchel/fldc-issues/issues/29#issuecomment-174881602>
> .
>



-- 
<http://jay-epstein.com>
*Jay Epstein, LLC. *
Professional Web Development
http://www.jay-epstein.com
954.683.3182

**Comment by rje1953** [comment]
We made a commit to DEV that added 1 line of code to the custom Eventbrite Integration module to pull data only published events. We tested it and it works but you must first enable the module and then set the Bio Field mappings. Then run CRON several times to clear out the remains of last year's data from the Queue Table. John, can you please deploy this code to Stage and Production? Then we will update the Bio Field Mappings and ensure the module is enabled and run cron to test. At this point we should not turn off the module because it seems to clear out the Bio Field Mappings.

**Comment by rje1953** [comment]
Sorry didn't mean to close this, only comment.

**Comment by JCL324** [comment]
Ok done.  Code is on Staging and Prod.

@mherchel, did you make that tag on Prod from the Staging branch?  Isn't it time to just go back to having Master as the main branch?

**Comment by mherchel** [comment]
After I deployed the code to prod, I downsynced the code/db/files from prod to both staging and dev

**Comment by JCL324** [comment]
Um, that's not what I asked. When you "deployed code to prod" what specifically did you do? Did you drag the Staging code over to Prod thus making a tag labeled 2016-01-21? Why are we not making tags off of the master branch?

**Comment by rje1953** [comment]
Hi John, I'm not seeing any published content of type = Bio on the PROD site. It works just fine on the STAGING site. This leads me to think that the code did not get deployed to PROD. Can you please check? Thanks.

**Comment by JCL324** [comment]
If it's working on Staging then it has to on Prod since the current tag on Prod was made from Staging.  But I just looked on Prod, and there are 4 people now on the attendees page!  Should be 17, is it just more cron runs to get them all over? And I checked on the Content page, set filters for Bio and published and there are 4 there.

**Comment by rje1953** [comment]
OK Then it works and just needs more CRON runs. I was impatient. Thanks. I'll check later on but we should eventually see all 16 or whatever the number is currently.

**Comment by mherchel** [comment]
Seems to be working. I went ahead and enabled it. https://www.fldrupal.camp/community/attendees
